name: MLflow CI

on:
  push:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mlflow scikit-learn pandas dagshub

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/putriipuspita/eksperimen-sml.mlflow
          MLFLOW_TRACKING_USERNAME: putriipuspita
          MLFLOW_TRACKING_PASSWORD: ca4dfce32691ae790f728615d60681bffdc45bbc
        run: |
          cd MLProject
          mlflow run . --env-manager=local